spring.application.name=demo
spring.datasource.url=postgresql://neondb_owner:npg_VIuhpDk27WKm@ep-fancy-meadow-aphirp5e.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=9999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect